# Generated by Django 4.0.3 on 2022-04-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_profile_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id2',
            field=models.IntegerField(null=True),
        ),
    ]
