# Generated by Django 4.0.3 on 2022-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
